// Generated by CoffeeScript 1.10.0
var gcd, i, isOdd, j, stdin;

for (i = j = 0; j <= 5; i = ++j) {
  console.log("Hello " + i);
}

stdin = process.openStdin();

stdin.setEncoding('utf8');

stdin.on('data', function(input) {
  var name;
  name = input.trim();
  if (name === 'exit') {
    process.exit();
  }
  console.log("Hello " + name);
  return console.log("Enter another name or 'exit' to exit");
});

console.log('Enter your name');

isOdd = function(n) {
  return n % 2 === 1;
};

odds.reduce(function(a, b) {
  return a + b;
});

gcd = function(a, b) {
  if (b === 0) {
    return a;
  } else {
    return gcd(b, a % b);
  }
};

$("#button").click(function() {
  var a, b;
  a = $("#a").val();
  b = $("#b").val();
  return $("#c").html(gcd(a, b));
});
